### ISSUE TITLE
Follow DRY

### ISSUE THREAD

**Issue by d-shaktiranjan** [partha7978/portfolio#1]
## Issue type:- Enhancement

Hey @partha7978 How are you?
Hope everything doings well, I just find your [this](https://github.com/partha7978/portfolio/blob/main/scripts/card_hover.js) js codebase is not following DRY concept, so I arising this enhancement issue,
Hope you look into this, and I just add my personal suggestion or reference for you.

<hr>

## Reference from my side

```javascript

let content = document.getElementsByClassName("classNameHere");

for (let item of content) {
    let label = document.getElementById(`ID_Here`);
    item.addEventListener("mouseover", () => {
        label.style.visibility = "visible";
    })
    item.addEventListener("mouseout", () => {
        label.style.visibility = "hidden";
    })
}

**Comment by partha7978** [comment]
Thank you for helping me out. But it's not working.
